# Generated by Django 5.2.4 on 2026-06-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("cashier", "Cashier"),
                    ("kitchen", "Chef"),
                ],
                default="cashier",
                max_length=20,
            ),
        ),
    ]
