# Generated by Django 5.2.4 on 2026-06-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Coupon", "Coupon (Code based)"),
                            ("Automated Promo", "Automated (Automatic discount)"),
                        ],
                        default="Coupon",
                        max_length=50,
                    ),
                ),
                ("code", models.CharField(blank=True, default="", max_length=50)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("Percentage", "Percentage"),
                            ("Fixed Amount", "Fixed Amount"),
                        ],
                        default="Percentage",
                        max_length=50,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "min_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("All", "All Products"),
                            ("Category", "Specific Category"),
                            ("Product", "Specific Product"),
                        ],
                        default="All",
                        max_length=50,
                    ),
                ),
                (
                    "target_value",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("activated", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
