# Generated by Django 5.2.4 on 2026-06-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promotion",
            name="end_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="start_date",
            field=models.DateField(),
        ),
    ]
