# Generated by Django 5.2.4 on 2026-06-14 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="name",
            field=models.CharField(default="Promotion", max_length=150),
        ),
        migrations.AddField(
            model_name="coupon",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("all", "All"),
                    ("category", "Category"),
                    ("product", "Product"),
                ],
                default="all",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="target_value",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="coupon",
            name="type",
            field=models.CharField(
                choices=[("Coupon", "Coupon"), ("Automated Promo", "Automated Promo")],
                default="Coupon",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="expiry_date",
            field=models.DateField(default="2027-12-31"),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="max_uses",
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
