# Generated by Django 5.2.4 on 2026-06-14 02:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "promotions",
            "0002_coupon_name_coupon_target_type_coupon_target_value_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="expiry_date",
            field=models.DateField(default=datetime.date(2027, 12, 31)),
        ),
    ]
