# Generated by Django 5.2.4 on 2026-06-13 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Floor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Table identifier like f1, s2", max_length=10
                    ),
                ),
                ("number", models.CharField(blank=True, default="", max_length=10)),
                ("capacity", models.PositiveIntegerField(default=4)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("occupied", "Occupied"),
                            ("reserved", "Reserved"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tables",
                        to="floors.floor",
                    ),
                ),
            ],
            options={
                "ordering": ["floor", "name"],
                "unique_together": {("floor", "name")},
            },
        ),
    ]
